### ISSUE TITLE
TransactionRollbackError:

### ISSUE THREAD

**Issue by sdalexander** [ingadhoc/odoo-etl#8]
Hi  I have installed the odoo_etl module and set up a migration but when I click on 'Read Models' I am getting the following errors

2015-12-14 09:26:55,204 19060 ERROR spectrum_911 openerp.sql_db: bad query: INSERT INTO "etl_external_model" ("id", "name", "sequence", "manager_id", "model", "type", "fields_to_read", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('etl_external_model_id_seq'), 'Invoice Line', 1820, 1, 'account.invoice.line', 'source', '[''name'']', 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
Traceback (most recent call last):
  File "/home/odoo/odoo8/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update
CONTEXT:  SQL statement "SELECT 1 FROM ONLY "public"."res_users" x WHERE "id" OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x"
Do you have any ideas on how to get around this error?

Steve

**Comment by sdalexander** [comment]
I have found the issue. I installed the module in an existing db. need's to be installed into an EMPTY database.
My own fault.

**Comment by sbpro86** [comment]
I confirm. I have the same problem and it works well on EMPTY database.

Thanks.

**Comment by feketemihai** [comment]
There is no issue...if you read the small doc you need a empty database for the etl module and another 2 databases as the source one and the target one.

**Comment by sbpro86** [comment]
I don't found the small doc :) except one in espagnol

**Comment by sdalexander** [comment]
Hi Slimwhen you look in that document in Google there is an option under tools to translate the document into your local languagesteveOn 19 February 2016 at 11:16 Slim Bhiri - سليم البحيري notifications@github.com wrote:I don't found the small doc :) except one in espagnol—Reply to this email directly or view it on GitHub.

**Comment by jjscarafia** [comment]
Sorry for the lack of documentation and the ugly code, I do this a long
time ago and with hurry for a need a that moment

**Comment by sdalexander** [comment]
Hi JuanNo problem, the module was very useful.steveOn 19 February 2016 at 11:40 Juan José Scarafía notifications@github.com wrote:Sorry for the lack of documentation and the ugly code, I do this a long time ago and with hurry for a need a that moment  El vie., feb. 19, 2016 8:22, sdalexander notifications@github.com escribió:  > > > Hi Slimwhen you look in that document in Google there is an option under > tools to translate the document into your local languagesteveOn 19 February > 2016 at 11:16 Slim Bhiri - سليم البحيري notifications@github.com > wrote:I don't found the small doc :) except one in espagnol—Reply to this > email directly or view it on GitHub. > > — > Reply to this email directly or view it on GitHub > https://github.com/ingadhoc/odoo-etl/issues/8#issuecomment-186177205. >—Reply to this email directly or view it on GitHub.

**Comment by sbpro86** [comment]
Thank you Alexander for the info .. i haven't trust on manual copy/past google translation. I will do that now.

Thank you very much Juan, the module is very useful. If I had time i will try to write a draft documentation but unfortunately I can't know.
