### ISSUE TITLE
TypeError: must be string, not instance

### ISSUE THREAD

**Issue by sbpro86** [ingadhoc/odoo-etl#9]
Hi,

Thank you very much for this really great module. After using a clean database all the process works well except that when executing actions it always ends with this error and nothing is added to the destination db :

> 2016-02-19 02:22:32,551 5402 ERROR erp_chamsauto_com openerp.http: must be string, not instance
> Traceback (most recent call last):
>   File "/opt/odoo/openerp/http.py", line 115, in dispatch_rpc
>     result = dispatch(method, params)
>   File "/opt/odoo/openerp/service/model.py", line 37, in dispatch
>     res = fn(db, uid, _params)
>   File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
>     return f(dbname, *args, *_kwargs)
>   File "/opt/odoo/openerp/service/model.py", line 175, in execute
>     res = execute_cr(cr, uid, obj, method, _args, *_kw)
>   File "/opt/odoo/openerp/service/model.py", line 164, in execute_cr
>     return getattr(object, method)(cr, uid, _args, *_kw)
>   File "/opt/odoo/openerp/api.py", line 256, in wrapper
>     return old_api(self, _args, *_kwargs)
>   File "/opt/odoo/openerp/models.py", line 1057, in load
>     context=context, log=messages.append):
>   File "/opt/odoo/openerp/models.py", line 1233, in _convert_records
>     converted = convert(record, lambda field, err:\
>   File "/opt/odoo/openerp/addons/base/ir/ir_fields.py", line 81, in fn
>     converted[field], ws = converters[field](value)
>   File "/opt/odoo/openerp/api.py", line 254, in wrapper
>     return new_api(self, _args, *_kwargs)
>   File "/opt/odoo/openerp/addons/base/ir/ir_fields.py", line 236, in _str_to_datetime
>     value, DEFAULT_SERVER_DATETIME_FORMAT)
> TypeError: must be string, not instance

Have you please an idea on how to fix this ?

Regards,

**Comment by jjscarafia** [comment]
I've not used for v9 yet. It seams to be a issue with date date time format.
Check both users are in same language (old database and new database),
someone has already talk about this issue but I don't know the solution

**Comment by sbpro86** [comment]
Thank you Juan José for the response,

I'm using v8 for both source & destination dbs. I have also checked that users are in same language fr_FR in my case and also the same datetime, decimal & millions separator but still the same error and I notice now that the error is on the destination DB : 

> 2016-02-23 23:41:45,168 5402 INFO **etl_odoo_db** openerp.addons.etl.action: Loadding Data...
> 2016-02-23 23:41:45,235 5402 ERROR **dest_db** openerp.http: must be string, not instance
> Traceback (most recent call last):
>   File "/opt/odoo/openerp/http.py", line 115, in dispatch_rpc
>     result = dispatch(method, params)
>   File "/opt/odoo/openerp/service/model.py", line 37, in dispatch
>     res = fn(db, uid, _params)
>   File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
>     return f(dbname, *args, *_kwargs)
>   File "/opt/odoo/openerp/service/model.py", line 175, in execute
>     res = execute_cr(cr, uid, obj, method, _args, *_kw)
>   File "/opt/odoo/openerp/service/model.py", line 164, in execute_cr
>     return getattr(object, method)(cr, uid, _args, *_kw)
>   File "/opt/odoo/openerp/api.py", line 256, in wrapper
>     return old_api(self, _args, *_kwargs)
>   File "/opt/odoo/openerp/models.py", line 1057, in load
>     context=context, log=messages.append):
>   File "/opt/odoo/openerp/models.py", line 1233, in _convert_records
>     converted = convert(record, lambda field, err:\
>   File "/opt/odoo/openerp/addons/base/ir/ir_fields.py", line 81, in fn
>     converted[field], ws = converters[field](value)
>   File "/opt/odoo/openerp/api.py", line 254, in wrapper
>     return new_api(self, _args, *_kwargs)
>   File "/opt/odoo/openerp/addons/base/ir/ir_fields.py", line 236, in _str_to_datetime
>     value, DEFAULT_SERVER_DATETIME_FORMAT)
> TypeError: must be string, not instance

**Comment by sbpro86** [comment]
Can this be related to python version or any other vendor version ?

**Comment by jjscarafia** [comment]
Not sure.. When do you get this error? On module install? Are you using it on odoo v8? Empty db?

**Comment by sbpro86** [comment]
I get this error when I run actions with an ETL Manager and it appears after loading data from the source DB .. I have also tried on both production & local Ubuntu servers.

Thank.

**Comment by vkhalil** [comment]
Hi,

Same error for me when moving data from odoo 8 to odoo 8.

@slimit
Did you find a fix or workaround please ?

Thanks.
